SENSOR_DEFINITIONS = {
    0: {
        "name": "Active Power+",
        "obis": "1-0:1.4.0*255",
        "unit": "W",
        "scale": 0.1,
        "type": "uint32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    2: {
        "name": "Active Power-",
        "obis": "1-0:2.4.0*255",
        "unit": "W",
        "scale": 0.1,
        "type": "uint32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    4: {
        "name": "Reactive Power+",
        "obis": "1-0:3.4.0*255",
        "unit": "var",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    6: {
        "name": "Reactive Power-",
        "obis": "1-0:4.4.0*255",
        "unit": "var",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    16: {
        "name": "Apparent Power+",
        "obis": "1-0:9.4.0*255",
        "unit": "VA",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    18: {
        "name": "Apparent Power-",
        "obis": "1-0:10.4.0*255",
        "unit": "VA",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    24: {
        "name": "Power Factor",
        "obis": "1-0:13.4.0*255",
        "unit": "unitless",
        "scale": 0.001,
        "type": "int32",
        "device": "smartmeter",
    },
    26: {
        "name": "Supply Frequency",
        "obis": "1-0:14.4.0*255",
        "unit": "Hz",
        "scale": 0.001,
        "type": "uint32",
        "device": "smartmeter",
    },
    40: {
        "name": "Active Power+ (L1)",
        "obis": "1-0:21.4.0*255",
        "unit": "W",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    42: {
        "name": "Active Power- (L1)",
        "obis": "1-0:22.4.0*255",
        "unit": "W",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    44: {
        "name": "Reactive Power+ (L1)",
        "obis": "1-0:23.4.0*255",
        "unit": "var",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    46: {
        "name": "Reactive Power- (L1)",
        "obis": "1-0:24.4.0*255",
        "unit": "var",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    56: {
        "name": "Apparent Power+ (L1)",
        "obis": "1-0:29.4.0*255",
        "unit": "VA",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    58: {
        "name": "Apparent Power- (L1)",
        "obis": "1-0:30.4.0*255",
        "unit": "VA",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    60: {
        "name": "Current (L1)",
        "obis": "1-0:31.4.0*255",
        "unit": "A",
        "scale": 0.001,
        "type": "uint32",
        "device_class": "current",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    62: {
        "name": "Voltage (L1)",
        "obis": "1-0:32.4.0*255",
        "unit": "V",
        "scale": 0.001,
        "type": "uint32",
        "device_class": "voltage",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    64: {
        "name": "Power Factor (L1)",
        "obis": "1-0:33.4.0*255",
        "unit": "unitless",
        "scale": 0.001,
        "type": "int32",
        "device": "smartmeter",
    },
    80: {
        "name": "Active Power+ (L2)",
        "obis": "1-0:41.4.0*255",
        "unit": "W",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    82: {
        "name": "Active Power- (L2)",
        "obis": "1-0:42.4.0*255",
        "unit": "W",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    84: {
        "name": "Reactive Power+ (L2)",
        "obis": "1-0:43.4.0*255",
        "unit": "var",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    86: {
        "name": "Reactive Power- (L2)",
        "obis": "1-0:44.4.0*255",
        "unit": "var",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    96: {
        "name": "Apparent Power+ (L2)",
        "obis": "1-0:49.4.0*255",
        "unit": "VA",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    98: {
        "name": "Apparent Power- (L2)",
        "obis": "1-0:50.4.0*255",
        "unit": "VA",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    100: {
        "name": "Current (L2)",
        "obis": "1-0:51.4.0*255",
        "unit": "A",
        "scale": 0.001,
        "type": "uint32",
        "device_class": "current",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    102: {
        "name": "Voltage (L2)",
        "obis": "1-0:52.4.0*255",
        "unit": "V",
        "scale": 0.001,
        "type": "uint32",
        "device_class": "voltage",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    104: {
        "name": "Power Factor (L2)",
        "obis": "1-0:53.4.0*255",
        "unit": "unitless",
        "scale": 0.001,
        "type": "int32",
        "device": "smartmeter",
    },
    120: {
        "name": "Active Power+ (L3)",
        "obis": "1-0:61.4.0*255",
        "unit": "W",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    122: {
        "name": "Active Power- (L3)",
        "obis": "1-0:62.4.0*255",
        "unit": "W",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    124: {
        "name": "Reactive Power+ (L3)",
        "obis": "1-0:63.4.0*255",
        "unit": "var",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    126: {
        "name": "Reactive Power- (L3)",
        "obis": "1-0:64.4.0*255",
        "unit": "var",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    136: {
        "name": "Apparent Power+ (L3)",
        "obis": "1-0:69.4.0*255",
        "unit": "VA",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    138: {
        "name": "Apparent Power- (L3)",
        "obis": "1-0:70.4.0*255",
        "unit": "VA",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    140: {
        "name": "Current (L3)",
        "obis": "1-0:71.4.0*255",
        "unit": "A",
        "scale": 0.001,
        "type": "uint32",
        "device_class": "current",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    142: {
        "name": "Voltage (L3)",
        "obis": "1-0:72.4.0*255",
        "unit": "V",
        "scale": 0.001,
        "type": "uint32",
        "device_class": "voltage",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    144: {
        "name": "Power Factor (L3)",
        "obis": "1-0:73.4.0*255",
        "unit": "unitless",
        "scale": 0.001,
        "type": "int32",
        "device": "smartmeter",
    },
    146: {
        "name": "Minimum Active Power+",
        "obis": None,
        "unit": "W",
        "scale": 0.1,
        "type": "uint32",
        "device": "smartmeter",
    },
    512: {
        "name": "Active energy+",
        "obis": "1-0:1.8.0*255",
        "unit": "Wh",
        "scale": 0.1,
        "type": "uint64",
        "device_class": "energy",
        "state_class": "total_increasing",
        "device": "smartmeter",
    },
    516: {
        "name": "Active energy-",
        "obis": "1-0:2.8.0*255",
        "unit": "Wh",
        "scale": 0.1,
        "type": "uint64",
        "device_class": "energy",
        "state_class": "total_increasing",
        "device": "smartmeter",
    },
    520: {
        "name": "Reactive energy+",
        "obis": "1-0:3.8.0*255",
        "unit": "varh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    524: {
        "name": "Reactive energy-",
        "obis": "1-0:4.8.0*255",
        "unit": "varh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    544: {
        "name": "Apparent energy+",
        "obis": "1-0:9.8.0*255",
        "unit": "VAh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    548: {
        "name": "Apparent energy-",
        "obis": "1-0:10.8.0*255",
        "unit": "VAh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    592: {
        "name": "Active energy+ (L1)",
        "obis": "1-0:21.8.0*255",
        "unit": "Wh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    596: {
        "name": "Active energy- (L1)",
        "obis": "1-0:22.8.0*255",
        "unit": "Wh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    600: {
        "name": "Reactive energy+ (L1)",
        "obis": "1-0:23.8.0*255",
        "unit": "varh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    604: {
        "name": "Reactive energy- (L1)",
        "obis": "1-0:24.8.0*255",
        "unit": "varh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    624: {
        "name": "Apparent energy+ (L1)",
        "obis": "1-0:29.8.0*255",
        "unit": "VAh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    628: {
        "name": "Apparent energy- (L1)",
        "obis": "1-0:30.8.0*255",
        "unit": "VAh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    672: {
        "name": "Active energy+ (L2)",
        "obis": "1-0:41.8.0*255",
        "unit": "Wh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    676: {
        "name": "Active energy- (L2)",
        "obis": "1-0:42.8.0*255",
        "unit": "Wh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    680: {
        "name": "Reactive energy+ (L2)",
        "obis": "1-0:43.8.0*255",
        "unit": "varh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    684: {
        "name": "Reactive energy- (L2)",
        "obis": "1-0:44.8.0*255",
        "unit": "varh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    704: {
        "name": "Apparent energy+ (L2)",
        "obis": "1-0:49.8.0*255",
        "unit": "VAh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    708: {
        "name": "Apparent energy- (L2)",
        "obis": "1-0:50.8.0*255",
        "unit": "VAh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    752: {
        "name": "Active energy+ (L3)",
        "obis": "1-0:61.8.0*255",
        "unit": "Wh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    756: {
        "name": "Active energy- (L3)",
        "obis": "1-0:62.8.0*255",
        "unit": "Wh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    760: {
        "name": "Reactive energy+ (L3)",
        "obis": "1-0:63.8.0*255",
        "unit": "varh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    764: {
        "name": "Reactive energy- (L3)",
        "obis": "1-0:64.8.0*255",
        "unit": "varh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    784: {
        "name": "Apparent energy+ (L3)",
        "obis": "1-0:69.8.0*255",
        "unit": "VAh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    788: {
        "name": "Apparent energy- (L3)",
        "obis": "1-0:70.8.0*255",
        "unit": "VAh",
        "scale": 0.1,
        "type": "uint64",
        "device": "smartmeter",
    },
    49206: {
        "name": "Enector_status",
        "unit": "",
        "scale": 1,
        "type": "uint64",
        "device": "wallbox",
        "device_class": "enum",
        "state_class": None,
        "map": {
            0: "Unbekannt",
            1: "Offline",
            2: "Verbunden",
            3: "Pausiert",
            4: "Probing",
            5: "Ladend",
            6: "Kommunikationsfehler",
            7: "Service Mode",
        },
    },
    49218: {
        "name": "Enector_L1",
        "unit": "A",
        "scale": 0.001,
        "type": "uint32",
        "device_class": "current",
        "state_class": "measurement",
        "device": "wallbox",
    },
    49246: {
        "name": "Enector_Ladeleistung",
        "unit": "W",
        "scale": 0.001,
        "type": "uint64",
        "device_class": "power",
        "state_class": "measurement",
        "device": "wallbox",
    },
    49254: {
        "name": "Enector_geladene_Energie",
        "unit": "Wh",
        "scale": 0.001,
        "type": "uint64",
        "device_class": "energy",
        "state_class": "total_increasing",
        "device": "wallbox",
    },
    40972: {
        "name": "Grid power Total",
        "type": "int32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    40974: {
        "name": "Sum output inverter AC",
        "type": "int32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    40976: {
        "name": "Sum pv power inverter DC",
        "type": "int32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    40982: {
        "name": "Home consumption",
        "type": "int32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    40984: {
        "name": "Sum battery charge/discharge DC",
        "type": "int32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    40986: {
        "name": "System state of charge",
        "type": "uint16",
        "unit": "%",
        "device_class": "battery",
        "device": "smartmeter",
    },
    40988: {
        "name": "Home consumption from PV",
        "type": "uint32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    40990: {
        "name": "Home consumption from battery",
        "type": "uint32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    40992: {
        "name": "Home consumption from grid",
        "type": "uint32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    40994: {
        "name": "Active charge mode",
        "type": "uint16",
        "unit": "",
        "device": "smartmeter",
    },
    40996: {
        "name": "Sum wallbox charge power total",
        "type": "uint32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    40998: {
        "name": "Sum wallbox charge power PV",
        "type": "uint32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    41000: {
        "name": "Sum wallbox charge power battery",
        "type": "uint32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    41002: {
        "name": "Sum wallbox charge power grid",
        "type": "uint32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    41010: {
        "name": "Sum inverter control values",
        "type": "uint32",
        "unit": "W",
        "device_class": "power",
        "device": "smartmeter",
    },
    41012: {
        "name": "Curtailment active",
        "type": "uint16",
        "unit": "",
        "device": "smartmeter",
    },
}
